### ISSUE TITLE
7.1.1 booting?

### ISSUE THREAD

**Issue by Pablito2020** [LinerSRT/android_device_thl4000#3]
Is the 7.1.1 branch booting?
Trying to adapt my cm13.0 zormax device tree to nougat but no luck...
THanks in advance

**Comment by LinerSRT** [comment]
7.0 booted, in 7.1.1 need replace libsproutmanager.so from another work sprout rom

**Comment by Pablito2020** [comment]
okay, thanks! :grinning:
